// ======================================================================
// This file is a part of the ProgrammerStenoTutor project
//
// Copyright (C) 2017  Vissale NEANG <fromtonrouge at gmail dot com>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
// ======================================================================

#pragma once

#include "Models/TreeItemModel.h"
#include <QtCore/QByteArray>
#include <QtCore/QBitArray>
#include <QtCore/QVector>
#include <QtCore/QPair>

class KeyboardTreeItem;
class KeyboardModel : public TreeItemModel
{
    Q_OBJECT

signals:
    void keyboardLoaded();
    void linkedKeycapsStates(const QVector<QPair<QString, bool>>& keycapsStates);

public:
    KeyboardModel(QObject* pParent = nullptr);
    ~KeyboardModel();

    static QModelIndex getParentKeycap(const QModelIndex& indexInKeycapHierarchy);
    void loadKeyboardSvgFile(const QString& sSvgFilePath);
    void loadKeyboardSvg(const QByteArray& svgContent);
    const QByteArray& getSvgContent() const {return _svgContent;}
    void setSvgContent(const QByteArray& svgContent);
    KeyboardTreeItem* getKeyboardTreeItem() const;
    void setKeyboardTreeItem(KeyboardTreeItem* pKeyboardTreeItem);
    QModelIndex getKeyboardIndex() const;
    QModelIndex getKeycapsIndex() const;
    virtual QStringList mimeTypes() const override;
    virtual bool canDropMimeData(const QMimeData* pData, Qt::DropAction action, int iRow, int iColumn, const QModelIndex& parent) const override;

public slots:
    void selectLinkedKeys(const QString& sDictionaryName, const QBitArray& inputsKeysBits);

private:
    QByteArray _svgContent; ///< Content of a svg file generated by http://www.keyboard-layout-editor.com and edited in Inkscape.
};

