// ======================================================================
// This file is a part of the ProgrammerStenoTutor project
//
// Copyright (C) 2017  Vissale NEANG <fromtonrouge at gmail dot com>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
// ======================================================================

#pragma once

#include <QtGui/QStandardItemModel>
#include <QtCore/QByteArray>

class KeyboardPropertiesModel : public QStandardItemModel
{
    Q_OBJECT

signals:
    void keyboardLoaded();

public:
    enum PropertyType
    {
        SvgFile,
        KeycapsRoot,
        Keycap,
        Attribute
    };

    enum UserRole
    {
        PropertyTypeRole = Qt::UserRole + 1, ///< int.
        RotationAngleRole, ///< qreal.
        RotationOriginRole, ///< qreal.
        OuterBorderRole, ///< QRectF.
        MaxUserRole
    };

public:
    KeyboardPropertiesModel(QObject* pParent = nullptr);
    ~KeyboardPropertiesModel();

    static QModelIndex getParentKeycap(const QModelIndex& indexInKeycapHierarchy);
    void loadKeyboardSvgFile(const QString& sSvgFilePath);
    void loadKeyboardSvg(const QByteArray& svgContent);
    const QByteArray& getSvgContent() const {return _svgContent;}
    void setSvgContent(const QByteArray& svgContent) {_svgContent = svgContent;}

private slots:
    void onModelReset();

private:
    QByteArray _svgContent; ///< Content of a svg file generated by http://www.keyboard-layout-editor.com and edited in Inkscape.
};

